name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b3c057ad64a9a392fab14392f78351eea7e6ff86651328de4525bd2c890b41"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
