name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f06041eea1aa864e2987522e235239acd728aa84ab7627fdab8114ea158a5f1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
