name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a04e70c30099b5fd326092a2533c45594d07d401cd84bd170c2ad87099cbea1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
