name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3de61f92b2c178b28bfe2d932641f3f1ac139ee291ce805b01b539a3523b6463"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
