name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ad28664e924938b5d8e02230a9261db7d329b77a4fc1cc6a6641997ed03e7e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
