name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c878cb98deb32da116d62b131c336b19d21643ae1590d2f0a3e34bf6da53175"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
