name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f813fadeef91570f18a41ffc577c71b72021f82991f1088ab63b80ee05009b69"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
