name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e34ad8424c76f5e5d7fa43f401d85f074f2f589e4d6d3dd867ae1efe51e08fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
