name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beccf0d52f8303f386bc61879cec8b3de3c5b7e99b3141c28f86726effb8cc09"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
