name = "Firebomb 2"
author = "Khorne & Hri7566"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5728cdb5126912d1aa6f46e8085ff9bcaf843f38c7906771cad4beb3abcb9e4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
